# Generated by Django 3.2.8 on 2021-11-04 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writes',
            options={'ordering': ['paper_id', 'order']},
        ),
    ]
